"""
Documentation Generator

Generates comprehensive Markdown documentation for Python scripts.
Creates a .md file next to the script with detailed analysis following a structured template.
"""

from pathlib import Path
from typing import Dict, Any
import requests
from agents.pulsus.config.settings import load_settings
from agents.pulsus.ui import display_manager as ui
from colorama import Fore, Style

__domain__ = "documentation"
__action__ = "generate"


def generate_documentation_content(file_path: Path, content: str, ast_analysis: Dict,
                                   metadata: Dict, llm_understanding: str,
                                   existing_doc: str = None) -> str:
    """
    Generate or enhance comprehensive documentation content using LLM.

    Args:
        file_path: Path to the script
        content: Script content
        ast_analysis: AST analysis
        metadata: Module metadata
        llm_understanding: Previously generated understanding
        existing_doc: Existing documentation to enhance (optional)

    Returns:
        Markdown documentation content
    """
    settings = load_settings()

    # Build structured prompt for comprehensive documentation
    functions_list = "\n".join([
        f"- {f['name']}({', '.join(f['args'])}): {f['docstring'][:100]}"
        for f in ast_analysis.get('functions', [])
    ])

    classes_list = "\n".join([
        f"- {c['name']}: {c['docstring'][:100]}"
        for c in ast_analysis.get('classes', [])
    ])

    # Check if we're enhancing existing documentation
    if existing_doc:
        mode = "ENHANCE"
        doc_instruction = f"""
EXISTING DOCUMENTATION TO ENHANCE:
---
{existing_doc[:3000]}
---

Your task: Enhance and improve the existing documentation above. Keep what's good, add missing information, update outdated parts, and improve clarity.
"""
    else:
        mode = "CREATE"
        doc_instruction = "Your task: Create comprehensive documentation from scratch."

    prompt = f"""{"ENHANCE" if existing_doc else "CREATE"} comprehensive documentation in Markdown format for this Python script.

{doc_instruction}

File: {file_path.name}
Path: {file_path}

Functions:
{functions_list or "None"}

Classes:
{classes_list or "None"}

Code Sample (first 5000 chars):
```python
{content[:5000]}
```

{"Enhance the existing documentation and " if existing_doc else "Create detailed documentation "}following this structure:

# {file_path.name}

## Overview
[2-3 paragraphs explaining purpose, main functionality, and use cases]

## Features
- [Key feature 1]
- [Key feature 2]
- [etc.]

## Installation & Dependencies
[List required packages and installation instructions]

## Usage

### Basic Usage
[Simple example of how to use the script]

### Advanced Usage
[More complex examples if applicable]

## API Reference

### Functions
[For each main function: signature, parameters, return value, description]

### Classes
[For each class: purpose, main methods, usage examples]

## Implementation Details
[Technical notes about the implementation approach]

## Examples
[Practical code examples showing real usage]

## Notes
[Important considerations, limitations, or gotchas]

---
*Auto-generated by Pulsus on {file_path.as_posix()}*

Write in clear, professional technical documentation style. Be comprehensive but concise."""

    try:
        if existing_doc:
            ui.pulsus("Enhancing existing documentation...")
        else:
            ui.pulsus("Generating comprehensive documentation...")
        print(f"{Fore.WHITE + Style.DIM}This may take 30-60 seconds...{Style.RESET_ALL}\n")

        response = requests.post(
            f"{settings.model.host}/api/generate",
            json={
                "model": settings.model.name,
                "prompt": prompt,
                "stream": True,
                "options": {
                    "temperature": 0.2,
                    "num_predict": 2048,  # Longer for comprehensive docs
                }
            },
            timeout=120,  # Longer timeout for documentation
            stream=True
        )

        if response.status_code == 200:
            full_text = ""
            for line in response.iter_lines():
                if line:
                    import json
                    try:
                        chunk = json.loads(line)
                        if "response" in chunk:
                            text = chunk["response"]
                            full_text += text
                            print(text, end='', flush=True)
                    except:
                        pass

            print("\n")
            return full_text.strip()
        else:
            return generate_fallback_documentation(file_path, ast_analysis, metadata, llm_understanding)

    except Exception as e:
        ui.error(f"LLM documentation generation failed: {e}")
        return generate_fallback_documentation(file_path, ast_analysis, metadata, llm_understanding)


def generate_fallback_documentation(file_path: Path, ast_analysis: Dict,
                                   metadata: Dict, llm_understanding: str) -> str:
    """
    Generate basic documentation when LLM is unavailable.

    Args:
        file_path: Path to the script
        ast_analysis: AST analysis
        metadata: Module metadata
        llm_understanding: Previously generated understanding

    Returns:
        Basic markdown documentation
    """
    doc = f"# {file_path.name}\n\n"
    doc += "## Overview\n\n"
    doc += f"{llm_understanding}\n\n"

    # Metadata
    if metadata.get('domain') or metadata.get('action'):
        doc += "## Metadata\n\n"
        if metadata.get('domain'):
            doc += f"- **Domain**: {metadata['domain']}\n"
        if metadata.get('action'):
            doc += f"- **Action**: {metadata['action']}\n"
        doc += "\n"

    # Functions
    if ast_analysis.get('functions'):
        doc += "## Functions\n\n"
        for func in ast_analysis['functions']:
            args = ', '.join(func['args'])
            doc += f"### `{func['name']}({args})`\n\n"
            if func['docstring']:
                doc += f"{func['docstring']}\n\n"
            doc += f"**Line**: {func['line']}\n\n"

    # Classes
    if ast_analysis.get('classes'):
        doc += "## Classes\n\n"
        for cls in ast_analysis['classes']:
            doc += f"### `{cls['name']}`\n\n"
            if cls['docstring']:
                doc += f"{cls['docstring']}\n\n"
            if cls['methods']:
                doc += f"**Methods**: {', '.join(cls['methods'])}\n\n"
            doc += f"**Line**: {cls['line']}\n\n"

    # Imports
    if ast_analysis.get('imports'):
        doc += "## Dependencies\n\n"
        for imp in ast_analysis['imports'][:20]:
            doc += f"- `{imp}`\n"
        doc += "\n"

    doc += "---\n"
    doc += f"*Auto-generated documentation by Pulsus*\n"

    return doc


def handle(file_path: Path, content: str, ast_analysis: Dict,
          metadata: Dict, llm_understanding: str) -> Dict[str, Any]:
    """
    Generate or enhance documentation for a script.

    Args:
        file_path: Path to the script
        content: Script content
        ast_analysis: AST analysis
        metadata: Module metadata
        llm_understanding: Previously generated understanding

    Returns:
        Result dictionary
    """
    # Check for existing documentation
    from agents.pulsus.workflows.tools.analyze.doc_scanner import load_existing_documentation

    existing_doc = load_existing_documentation(file_path)

    # Generate or enhance documentation content
    doc_content = generate_documentation_content(
        file_path, content, ast_analysis, metadata, llm_understanding, existing_doc
    )

    # Create .md file path
    doc_path = file_path.with_suffix('.md')

    # Save documentation
    try:
        doc_path.write_text(doc_content, encoding='utf-8')

        if existing_doc:
            ui.success(f"Documentation enhanced: {doc_path}")
        else:
            ui.success(f"Documentation created: {doc_path}")

        return {
            "status": "success",
            "doc_path": str(doc_path),
            "mode": "enhanced" if existing_doc else "created",
            "message": f"Documentation {'enhanced' if existing_doc else 'generated'}: {doc_path.name}"
        }

    except Exception as e:
        ui.error(f"Failed to save documentation: {e}")
        return {
            "status": "error",
            "message": str(e)
        }


if __name__ == "__main__":
    print("Documentation Generator - Test mode")
    print("Use via @path command in Pulsus")
